#obj-$(CONFIG_YZS_DLP) += dlp3438.o
#obj-$(CONFIG_YZS_POWER_DLP) += power_dlp3438.o
#obj-$(CONFIG_AML_DLP_POWER) += power_dlp_gpio.o
#obj-$(CONFIG_AML_DLP) += power_dlp_test.o
obj-$(CONFIG_AML_FAN) += fan_max6.o

	#obj-m := fan_driver.o
	#fan_driver-y:= fan.o
