#obj-$(CONFIG_YZS_DLP) += dlp3438.o
#obj-$(CONFIG_YZS_POWER_DLP) += power_dlp3438.o
#obj-$(CONFIG_AML_DLP_POWER) += power_dlp_gpio.o
#obj-$(CONFIG_AML_DLP) += power_dlp_test.o
obj-$(CONFIG_AML_DLP) += jonah-dlp3438.o

	#obj-m := m_gpio.o
	#obj-m := dlp_driver.o
	#dlp_driver-y:= dlp3438.o
	#m_gpio-y:= power_dlp_test.o
	#obj-m := dlp_driver.o
	#dlp_driver-y:= jonah-dlp3438.o
